import mongoose from 'mongoose';

const ExposureCaseSchema = new mongoose.Schema({
  caseKey: { type: String, required: true, unique: true, index: true },
  borrowerName: { type: String, default: '' },
  regNo: { type: String, default: '' },
  loanId: { type: String, default: '' },
  productName: { type: String, default: '' },
  branch: { type: String, default: '' },
  loanOfficer: { type: String, default: '' },
  phone: { type: String, default: '' },
  collateral: { type: String, default: '' },
  currency: { type: String, default: 'MNT' },
  interestRate: { type: Number, default: 0 },
  startDate: { type: String, default: '' },
  endDate: { type: String, default: '' },
  originalAmount: { type: Number, default: 0 },
  principalDebt: { type: Number, default: 0 },
  interestDebt: { type: Number, default: 0 },
  regularizationAmount: { type: Number, default: 0 },
  contactNote: { type: String, default: '' },
  lastContactDate: { type: String, default: '' },
  currentOutstandingBalance: { type: Number, default: 0 },
  currentOverdueAmount: { type: Number, default: 0 },
  currentOverdueDays: { type: Number, default: 0 },
  classification: { type: String, default: '' },
  overdueBucket: { type: String, default: '' },
  sourceSnapshot: {
    snapshotId: { type: mongoose.Schema.Types.ObjectId, ref: 'ExposureSnapshot', default: null },
    snapshotLabel: { type: String, default: '' },
  },
  assignee: {
    userId: { type: String, default: '' },
    name: { type: String, default: '' },
  },
  actionMeasures: { type: [String], default: [] },
  recommendedActions: { type: [String], default: [] },
  actionPlan: { type: String, default: '' },
  notes: { type: String, default: '' },
  status: {
    type: String,
    default: 'open',
    enum: ['open', 'monitoring', 'promise_to_pay', 'escalation', 'legal', 'resolved'],
  },
  isCurrentOverdue: { type: Boolean, default: true },
  isNewlyOverdue: { type: Boolean, default: false },
  firstDetectedAt: { type: Date, default: Date.now },
  lastSeenAt: { type: Date, default: Date.now },
  resolvedAt: { type: Date, default: null },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

export default mongoose.models.ExposureCase || mongoose.model('ExposureCase', ExposureCaseSchema);
