import { useEffect, useMemo, useState } from 'react';
import { Building2, FileText, History, Plus, RefreshCw, Save, SlidersHorizontal, Upload, UserPlus } from 'lucide-react';

const money = (value) => new Intl.NumberFormat('mn-MN', { maximumFractionDigits: 0 }).format(Number(value || 0));
const authHeaders = () => { const token = localStorage.getItem('loan_token'); if (token) return { Authorization: `Bearer ${token}` }; try { const auth = JSON.parse(localStorage.getItem('scm_auth') || '{}'); return auth.token ? { Authorization: `Bearer ${auth.token}` } : {}; } catch { return {}; } };
const incomeTypes = [['salary', 'Хөдөлмөрийн орлого'], ['passive', 'Идэвхгүй орлого'], ['contract', 'Гэрээт ажил'], ['cash_sale', 'Бэлэн борлуулалт'], ['other', 'Бусад орлого']];
const expenseGroups = [['A', 'A - Өрийн үүрэг'], ['B', 'B - Тогтмол'], ['C', 'C - Зайлшгүй'], ['D', 'D - Сонголтот'], ['E', 'E - Бизнес'], ['F', 'F - Шилжүүлэг / бэлэн']];
const blankSubject = { entityType: 'individual', accountHolderName: '', industryCode: '', industryName: '' };

export default function StatementWorkbench({ apiUrl }) {
  const [bootstrap, setBootstrap] = useState({ industries: [], rules: [], incomeWeights: {}, dtiDefaults: {} });
  const [files, setFiles] = useState([]); const [fileKey, setFileKey] = useState(0);
  const [analysis, setAnalysis] = useState(null); const [subject, setSubject] = useState(blankSubject);
  const [review, setReview] = useState({ dtiLimit: 55, incomeWeights: {}, overrides: [] }); const [savedReview, setSavedReview] = useState(null);
  const [history, setHistory] = useState([]); const [filter, setFilter] = useState('all'); const [showHistory, setShowHistory] = useState(false);
  const [ruleDraft, setRuleDraft] = useState({ keyword: '', direction: 'expense', category: '', incomeType: '', expenseGroup: 'F', eligiblePercent: 0 });
  const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const request = async (path, options = {}) => { const response = await fetch(`${apiUrl}${path}`, { ...options, headers: { ...authHeaders(), ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || 'Үйлдэл амжилтгүй боллоо.'); return body; };
  const loadHistory = async () => { try { setHistory(await request('/api/statement-workbench/reviews')); } catch { /* optional list */ } };

  useEffect(() => { request('/api/statement-workbench/bootstrap').then((data) => { setBootstrap(data); setReview((old) => ({ ...old, dtiLimit: data.dtiDefaults?.individual || 55, incomeWeights: data.incomeWeights || {} })); }).catch((error) => setMessage(error.message)); loadHistory(); }, [apiUrl]);

  const result = useMemo(() => {
    if (!analysis) return null;
    const overrides = new Map((review.overrides || []).map((item) => [item.transactionKey, item]));
    const transactions = (analysis.transactions || []).map((item, index) => {
      const transactionKey = `${item.date || ''}|${item.direction || ''}|${Number(item.amount || 0)}|${String(item.description || '').slice(0, 80)}|${index}`;
      const rule = (bootstrap.rules || []).find((candidate) => candidate.isActive !== false && (candidate.direction === 'any' || candidate.direction === item.direction) && String(item.description || '').toLowerCase().includes(String(candidate.keyword || '').toLowerCase()));
      const override = overrides.get(transactionKey); const category = override?.category || rule?.category || item.category || '';
      const incomeType = override?.incomeType || rule?.incomeType || (item.direction === 'income' ? 'other' : ''); const expenseGroup = override?.expenseGroup || rule?.expenseGroup || '';
      const eligiblePercent = item.direction === 'income' ? Number(override?.eligiblePercent ?? rule?.eligiblePercent ?? review.incomeWeights[incomeType] ?? review.incomeWeights.other ?? 0) : 0;
      const needsReview = !category || /ангилагдаагүй|unclassified|unknown/i.test(String(category));
      return { ...item, transactionKey, category: category || 'Ангилагдаагүй', incomeType, expenseGroup, eligiblePercent, ruleMatched: Boolean(rule), manuallyReviewed: Boolean(override), needsReview };
    });
    const months = Math.max(1, Number(analysis.frontSheet?.coveredMonths || analysis.monthlySummary?.length || 1));
    const eligibleIncome = transactions.filter((item) => item.direction === 'income').reduce((sum, item) => sum + Number(item.amount || 0) * item.eligiblePercent / 100, 0);
    const debt = transactions.filter((item) => item.direction === 'expense' && item.expenseGroup === 'A').reduce((sum, item) => sum + Number(item.amount || 0), 0);
    const monthlyIncome = eligibleIncome / months; const monthlyDebt = debt / months;
    return { transactions, summary: { months, monthlyIncome, monthlyDebt, dti: monthlyIncome ? monthlyDebt / monthlyIncome * 100 : 0, needsReview: transactions.filter((item) => item.needsReview).length } };
  }, [analysis, bootstrap.rules, review]);
  const shown = (result?.transactions || []).filter((item) => filter === 'all' || (filter === 'review' && item.needsReview) || (filter === 'income' && item.direction === 'income') || (filter === 'expense' && item.direction === 'expense') || (filter === 'debt' && item.expenseGroup === 'A'));
  const accounts = useMemo(() => { if (!analysis) return []; const rows = Array.isArray(analysis.accounts) && analysis.accounts.length ? analysis.accounts : [analysis.frontSheet || {}]; return rows.map((row, index) => ({ ...row, _key: `${row.accountNumber || 'account'}-${index}` })); }, [analysis]);
  const patch = (transactionKey, values) => setReview((old) => { const prior = old.overrides.find((item) => item.transactionKey === transactionKey) || { transactionKey }; return { ...old, overrides: [...old.overrides.filter((item) => item.transactionKey !== transactionKey), { ...prior, ...values }] }; });
  const startNew = () => { if (analysis && !window.confirm('Одоогийн хадгалаагүй өөрчлөлтүүдийг орхих уу?')) return; setFiles([]); setFileKey((n) => n + 1); setAnalysis(null); setSubject(blankSubject); setReview({ dtiLimit: bootstrap.dtiDefaults?.individual || 55, incomeWeights: bootstrap.incomeWeights || {}, overrides: [] }); setSavedReview(null); setFilter('all'); setMessage('Шинэ шинжилгээнд дансны хуулгаа сонгоно уу.'); };
  const analyze = async () => { if (!files.length) return setMessage('Нэг эсвэл хэд хэдэн дансны хуулга сонгоно уу.'); setLoading(true); setMessage(''); try { const payload = new FormData(); files.forEach((file) => payload.append('bankStatements', file)); const data = await request('/api/loan-research/analyze-statement', { method: 'POST', body: payload }); setAnalysis(data); setSavedReview(null); setSubject((old) => ({ ...old, accountHolderName: old.accountHolderName || data.frontSheet?.customerName || '' })); setMessage('Уншилт дууслаа. Бүх гүйлгээг шалгаад кейс болгон хадгална.'); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  const save = async () => { if (!analysis) return; setLoading(true); setMessage(''); try { const sourceFiles = files.length ? files.map((file, index) => ({ name: file.name, size: file.size, ...(accounts[index] || {}) })) : (savedReview?.sourceFiles || []); const data = await request(savedReview ? `/api/statement-workbench/reviews/${savedReview._id}` : '/api/statement-workbench/reviews', { method: savedReview ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(savedReview ? { subject, review, status: 'reviewed' } : { subject, sourceFiles, analysis, review }) }); setSavedReview(data); setMessage(`Кейс ${data.reference || ''} хадгалагдлаа.`); loadHistory(); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  const openReview = async (id) => { setLoading(true); try { const data = await request(`/api/statement-workbench/reviews/${id}`); setSavedReview(data); setAnalysis(data.analysis); setSubject(data.subject || blankSubject); setReview({ dtiLimit: data.review?.dtiLimit || 55, incomeWeights: data.review?.incomeWeights || bootstrap.incomeWeights || {}, overrides: data.review?.overrides || [] }); setFiles([]); setFileKey((n) => n + 1); setShowHistory(false); setFilter('all'); setMessage(`Кейс ${data.reference || ''} нээгдлээ.`); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  const convert = async () => { if (!savedReview?._id) return setMessage('Эхлээд кейсийг хадгална уу.'); setLoading(true); try { const data = await request(`/api/statement-workbench/reviews/${savedReview._id}/convert-customer`, { method: 'POST' }); setSavedReview((old) => ({ ...old, status: 'converted', convertedOnboardingId: data.onboardingId })); setMessage(`Харилцагчийн draft үүслээ: ${data.requestId || data.onboardingId}`); loadHistory(); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  const selectRule = (item) => { setRuleDraft({ keyword: item.description || '', direction: item.direction, category: item.category === 'Ангилагдаагүй' ? '' : item.category, incomeType: item.incomeType, expenseGroup: item.expenseGroup || 'F', eligiblePercent: item.eligiblePercent || 0 }); setMessage('Дүрмийн талбар сонгосон гүйлгээгээр бөглөгдлөө.'); };
  const addRule = async () => { if (!ruleDraft.keyword.trim() || !ruleDraft.category.trim()) return setMessage('Дүрэмд түлхүүр үг, ангилал шаардлагатай.'); setLoading(true); try { await request('/api/statement-workbench/rules', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(ruleDraft) }); const data = await request('/api/statement-workbench/bootstrap'); setBootstrap(data); setRuleDraft({ keyword: '', direction: 'expense', category: '', incomeType: '', expenseGroup: 'F', eligiblePercent: 0 }); setMessage('Компанийн дүрэм хадгалагдлаа.'); } catch (error) { setMessage(error.message === 'Forbidden' ? 'Компанийн дүрэм нэмэх эрх зөвхөн админд байна.' : error.message); } finally { setLoading(false); } };

  return <div className="space-y-5"><section className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Statement case workspace</p><h2 className="mt-1 text-lg font-bold text-slate-900">Дансны хуулгын кредит шинжилгээ</h2><p className="mt-1 text-sm text-slate-500">Шинжилгээ бүр тусдаа кейс болж хадгалагдана.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => { setShowHistory((v) => !v); loadHistory(); }} icon={<History size={16}/>}>Кейсийн түүх</Button><Button onClick={startNew} icon={<Plus size={16}/>}>Шинэ шинжилгээ</Button><button type="button" onClick={save} disabled={!analysis || loading} className="inline-flex items-center gap-2 rounded-lg bg-teal-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><Save size={16}/>{savedReview ? 'Өөрчлөлт хадгалах' : 'Кейс хадгалах'}</button></div></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Field label="Харилцагчийн төрөл"><select value={subject.entityType} onChange={(e) => { const entityType = e.target.value; setSubject((old) => ({ ...old, entityType })); setReview((old) => ({ ...old, dtiLimit: bootstrap.dtiDefaults?.[entityType] || 55 })); }}><option value="individual">Иргэн</option><option value="organization">Байгууллага</option></select></Field><Field label="Данс эзэмшигчийн нэр"><input value={subject.accountHolderName} onChange={(e) => setSubject((old) => ({ ...old, accountHolderName: e.target.value }))}/></Field><Field label="Үйл ажиллагааны салбар"><select value={subject.industryCode} onChange={(e) => { const sector = bootstrap.industries.find((item) => item.code === e.target.value); setSubject((old) => ({ ...old, industryCode: e.target.value, industryName: sector?.name || '' })); }}><option value="">Сонгох</option>{bootstrap.industries.map((item) => <option key={item.code} value={item.code}>{item.code} - {item.name}</option>)}</select></Field></div><div className="mt-4 flex flex-wrap items-center gap-3"><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-dashed border-teal-400 bg-teal-50 px-4 py-2.5 text-sm font-bold text-teal-800"><Upload size={16}/>Хуулга сонгох<input key={fileKey} type="file" multiple accept=".pdf,image/*" className="hidden" onChange={(e) => setFiles(Array.from(e.target.files || []))}/></label><span className="text-sm text-slate-500">{files.length ? `${files.length} файл: ${files.map((file) => file.name).join(', ')}` : 'PDF, PNG, JPG - хэд хэдэн хуулга сонгож болно'}</span><Button onClick={analyze} disabled={loading || !files.length}> {loading ? 'Уншиж байна...' : 'Уншиж, ангилах'} </Button></div></section>{message && <div className="rounded-lg border border-teal-100 bg-teal-50 px-4 py-3 text-sm font-semibold text-teal-900">{message}</div>}
    {showHistory && <HistoryTable history={history} openReview={openReview} reload={loadHistory}/>} {result && <><section className="grid gap-3 md:grid-cols-4"><Metric label="Дайчлах сарын орлого" value={`${money(result.summary.monthlyIncome)} MNT`}/><Metric label="Сарын өрийн төлөлт" value={`${money(result.summary.monthlyDebt)} MNT`}/><Metric label="ӨОХ / DTI" value={`${result.summary.dti.toFixed(1)}%`} alert={result.summary.dti > Number(review.dtiLimit)}/><Metric label="Review шаардлагатай" value={`${result.summary.needsReview} гүйлгээ`} alert={result.summary.needsReview > 0}/></section><AccountTable accounts={accounts} months={result.summary.months} currency={analysis.frontSheet?.currency}/><section className="grid gap-5 lg:grid-cols-[1fr_320px]"><TransactionTable items={shown} filter={filter} setFilter={setFilter} review={review} patch={patch} selectRule={selectRule}/><aside className="space-y-4"><section className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><SlidersHorizontal size={16} className="text-teal-700"/><h3 className="font-bold text-slate-900">Зээлийн тохиргоо</h3></div><label className="mt-4 block text-sm font-semibold text-slate-700">DTI босго: {review.dtiLimit}%<input type="range" min="1" max="100" value={review.dtiLimit} onChange={(e) => setReview((old) => ({ ...old, dtiLimit: Number(e.target.value) }))} className="mt-2 w-full accent-teal-700"/></label><div className="mt-4 space-y-2">{incomeTypes.map(([key, label]) => <label key={key} className="flex items-center justify-between gap-3 text-xs text-slate-600"><span>{label}</span><input type="number" min="0" max="100" value={review.incomeWeights[key] ?? 0} onChange={(e) => setReview((old) => ({ ...old, incomeWeights: { ...old.incomeWeights, [key]: Number(e.target.value) } }))} className="w-16 rounded border border-slate-300 p-1.5 text-right"/></label>)}</div></section><section className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><Building2 size={16} className="text-teal-700"/><h3 className="font-bold text-slate-900">Салбарын дүйцэл</h3></div><p className="mt-2 text-sm text-slate-600">{subject.industryName ? `${subject.industryCode}: ${subject.industryName}` : 'Салбар сонгоогүй байна.'}</p></section><button type="button" onClick={convert} disabled={!savedReview || loading || savedReview.status === 'converted'} className="flex w-full items-center justify-center gap-2 rounded-lg border border-teal-700 px-4 py-3 text-sm font-bold text-teal-800 disabled:cursor-not-allowed disabled:opacity-50"><UserPlus size={16}/>{savedReview?.status === 'converted' ? 'Харилцагчийн draft үүссэн' : 'Харилцагч болгох'}</button>{!savedReview && <p className="text-center text-xs text-slate-500">Кейс хадгалсны дараа идэвхжинэ.</p>}</aside></section><RuleEditor draft={ruleDraft} setDraft={setRuleDraft} addRule={addRule} rules={bootstrap.rules || []} loading={loading}/></>}</div>;
}

function Button({ onClick, icon, children, disabled }) { return <button type="button" onClick={onClick} disabled={disabled} className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700 disabled:opacity-50">{icon}{children}</button>; }
function Field({ label, children }) { return <label className="text-sm font-semibold text-slate-700">{label}<span className="mt-1 block [&_input]:block [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-slate-300 [&_input]:p-2.5 [&_select]:block [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-slate-300 [&_select]:p-2.5">{children}</span></label>; }
function Metric({ label, value, alert }) { return <div className={`rounded-lg border p-4 ${alert ? 'border-amber-200 bg-amber-50' : 'border-slate-200 bg-white'}`}><p className="text-xs font-semibold text-slate-500">{label}</p><p className={`mt-1 text-lg font-bold ${alert ? 'text-amber-800' : 'text-slate-900'}`}>{value}</p></div>; }
function HistoryTable({ history, openReview, reload }) { return <section className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Хадгалсан кейсүүд</h3><p className="text-xs text-slate-500">Нээгээд үргэлжлүүлэн засах эсвэл харилцагч болгоно.</p></div><button type="button" onClick={reload} className="rounded p-2 text-slate-500 hover:bg-slate-100" title="Шинэчлэх"><RefreshCw size={16}/></button></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Кейс</th><th className="p-3">Данс эзэмшигч</th><th className="p-3">Данс / хугацаа</th><th className="p-3">DTI</th><th className="p-3"></th></tr></thead><tbody>{history.length ? history.map((item) => <tr key={item._id} className="border-t border-slate-100"><td className="p-3 font-semibold">{item.reference || item._id.slice(-6)}</td><td className="p-3">{item.subject?.accountHolderName || '-'}</td><td className="p-3">{item.sourceFiles?.[0]?.accountNumber || '-'}<br/><span className="text-xs text-slate-400">{item.sourceFiles?.[0]?.periodStart || ''} {item.sourceFiles?.[0]?.periodEnd ? `- ${item.sourceFiles[0].periodEnd}` : ''}</span></td><td className="p-3">{Number(item.review?.result?.summary?.dti || 0).toFixed(1)}%</td><td className="p-3 text-right"><button type="button" onClick={() => openReview(item._id)} className="rounded border border-teal-700 px-3 py-1.5 text-xs font-bold text-teal-800">Нээх</button></td></tr>) : <tr><td colSpan="5" className="p-6 text-center text-slate-500">Хадгалсан кейс алга.</td></tr>}</tbody></table></div></section>; }
function AccountTable({ accounts, months, currency }) { return <section className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><FileText size={17} className="text-teal-700"/><h3 className="font-bold text-slate-900">Дансны мэдээлэл</h3></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Банк</th><th className="p-3">Дансны дугаар</th><th className="p-3">Хугацаа</th><th className="p-3 text-right">Эхний үлдэгдэл</th><th className="p-3 text-right">Эцсийн үлдэгдэл</th><th className="p-3">Валют</th></tr></thead><tbody>{accounts.map((account) => <tr key={account._key} className="border-t border-slate-100"><td className="p-3">{account.bankName || '-'}</td><td className="p-3 font-semibold">{account.accountNumber || '-'}</td><td className="p-3">{account.periodStart || '-'} - {account.periodEnd || '-'} <span className="text-xs text-slate-400">({account.coveredMonths || months} сар)</span></td><td className="p-3 text-right">{money(account.startingBalance)}</td><td className="p-3 text-right">{money(account.endingBalance)}</td><td className="p-3">{account.currency || currency || '-'}</td></tr>)}</tbody></table></div></section>; }
function TransactionTable({ items, filter, setFilter, review, patch, selectRule }) { return <div className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><div><h3 className="font-bold text-slate-900">Бүх гүйлгээ</h3><p className="text-xs text-slate-500">Ангилал засахад DTI шууд шинэчлэгдэнэ.</p></div><div className="flex flex-wrap gap-1">{[['all','Бүгд'],['review','Review'],['income','Орлого'],['expense','Зарлага'],['debt','Өрийн төлөлт']].map(([key,label]) => <button type="button" key={key} onClick={() => setFilter(key)} className={`rounded px-2.5 py-1.5 text-xs font-bold ${filter === key ? 'bg-teal-700 text-white' : 'bg-slate-100 text-slate-600'}`}>{label}</button>)}</div></div><div className="max-h-[560px] overflow-auto"><table className="w-full min-w-[940px] text-sm"><thead className="sticky top-0 bg-slate-50 text-left text-[11px] uppercase text-slate-500"><tr><th className="p-3">Огноо / утга</th><th className="p-3 text-right">Дүн</th><th className="p-3">Ангилал</th><th className="p-3">Орлого / зарлага</th><th className="p-3"></th></tr></thead><tbody>{items.map((item) => <tr key={item.transactionKey} className="border-t border-slate-100"><td className="p-3"><p className="font-semibold text-slate-800">{item.description || '-'}</p><p className="text-xs text-slate-400">{item.date} · {item.ruleMatched ? 'дүрэм' : item.manuallyReviewed ? 'ажилтан' : item.needsReview ? 'review шаардлагатай' : 'AI ангилал'}</p></td><td className={`p-3 text-right font-bold ${item.direction === 'income' ? 'text-emerald-700' : 'text-rose-700'}`}>{item.direction === 'income' ? '+' : '-'}{money(item.amount)}</td><td className="p-3"><input value={item.category} onChange={(e) => patch(item.transactionKey, { category: e.target.value })} className="w-44 rounded border border-slate-300 p-2 text-xs"/></td><td className="p-3">{item.direction === 'income' ? <select value={item.incomeType} onChange={(e) => patch(item.transactionKey, { incomeType: e.target.value, eligiblePercent: review.incomeWeights[e.target.value] ?? 0 })} className="rounded border border-slate-300 p-2 text-xs">{incomeTypes.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select> : <select value={item.expenseGroup} onChange={(e) => patch(item.transactionKey, { expenseGroup: e.target.value })} className="rounded border border-slate-300 p-2 text-xs"><option value="">Ангилагдаагүй</option>{expenseGroups.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select>}</td><td className="p-3 text-right"><button type="button" onClick={() => selectRule(item)} className="text-xs font-bold text-teal-700">Дүрэм болгох</button></td></tr>)}</tbody></table></div></div>; }
function RuleEditor({ draft, setDraft, addRule, rules, loading }) { return <section className="rounded-lg border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-900">Компанийн ангиллын дүрэм</h3><p className="mt-1 text-xs text-slate-500">Гүйлгээний “Дүрэм болгох” товчоор талбарыг бөглөөд админаар хадгална.</p><div className="mt-3 grid gap-2 md:grid-cols-6"><input placeholder="Түлхүүр үг" value={draft.keyword} onChange={(e) => setDraft((old) => ({ ...old, keyword: e.target.value }))} className="rounded border border-slate-300 p-2 text-sm"/><select value={draft.direction} onChange={(e) => setDraft((old) => ({ ...old, direction: e.target.value }))} className="rounded border border-slate-300 p-2 text-sm"><option value="income">Орлого</option><option value="expense">Зарлага</option><option value="any">Аль аль</option></select><input placeholder="Ангилал" value={draft.category} onChange={(e) => setDraft((old) => ({ ...old, category: e.target.value }))} className="rounded border border-slate-300 p-2 text-sm"/><select value={draft.incomeType} onChange={(e) => setDraft((old) => ({ ...old, incomeType: e.target.value }))} className="rounded border border-slate-300 p-2 text-sm"><option value="">Орлогын төрөл</option>{incomeTypes.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><select value={draft.expenseGroup} onChange={(e) => setDraft((old) => ({ ...old, expenseGroup: e.target.value }))} className="rounded border border-slate-300 p-2 text-sm">{expenseGroups.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={addRule} disabled={loading} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">Дүрэм хадгалах</button></div><div className="mt-4 flex flex-wrap gap-2">{rules.slice(0, 12).map((rule) => <span key={rule._id || `${rule.keyword}-${rule.category}`} className="rounded border border-slate-200 bg-slate-50 px-2 py-1 text-xs text-slate-600">{rule.keyword} → {rule.category}</span>)}</div></section>; }
